name: uchat
description: A new era chat application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.2

  # Data store
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.0
  path_provider: ^1.6.11

  # Data type
  uuid: 2.2.2

  # State management
  provider: ^4.0.0

  # Widget
  scrollable_positioned_list: ^0.1.8
  flutter_icons: ^1.1.0
  flutter_sticky_header: ^0.5.0
  flutter_easyloading: ^2.2.0
  awesome_dialog: ^1.1.3
  sticky_and_expandable_list: ^0.2.3
  loading: ^1.0.2
  flutter_slidable: ^0.5.7
  intl_phone_number_input: ^0.5.2+2
  pin_code_fields: ^6.0.1
  show_hide_fab: ^0.1.1
  modal_bottom_sheet: ^1.0.0+1
  focused_menu: ^1.0.1

  # Animation
  animate_do: ^1.7.3
  animated_size_and_fade: ^1.1.3

  # Notification
  onesignal_flutter: ^2.6.0

  # Helper
  url_launcher: ^5.7.10
  easy_debounce: ^1.0.2
  keyboard_visibility: 0.5.6
  package_info: ^0.4.0+13
  mime: ^0.9.7
  blurhash: ^0.2.1
  dart_date: ^1.0.7
  enum_to_string: ^1.0.13
  basic_utils: ^2.6.3
  recase: ^3.0.1
  vibration: ^1.7.2
  connectivity: ^2.0.2
  share: ^0.6.5+4
  gallery_saver: ^2.0.1

  # Text lib
  flutter_parsed_text: ^1.2.0

  # Icon
  font_awesome_flutter: ^8.8.0
  cupertino_icons: ^0.1.3

  # Badge
  badges: ^1.1.1

  # Http and socket helper lib
  dio: ^3.0.0
  socket_io_client: ^0.9.0

  # Image lib
  flutter_svg: ^0.19.0
  cached_network_image: ^2.3.3
  octo_image: ^0.3.0
  extended_image: ^1.3.0
  image: ^2.1.18
  photo_view: ^0.10.3
  flutter_blurhash: ^0.5.0

  # Language i18n
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter

  giphy_client: ^0.2.0
  emojis: 0.9.3

  stop_watch_timer: ^0.6.0+1
  flutter_dotenv: ^2.1.0

  # Dev logger
  logging: ^0.11.4

# This package is this list is not include to apk.
dev_dependencies:
  hive_generator: ^0.8.1
  build_runner: ^1.10.3
  #  screenshots: ^0.1.3

  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #fonts:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true